target_sources(SimpleMath
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vec2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vec3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vec4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Integer2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Math.hpp
)
