target_sources(Engine
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Component.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Component.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Composition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Composition.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CompositionInitializer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Engine.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineZilchStaticLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineZilchStaticLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LevelManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LevelManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Space.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TimeSpace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TimeSpace.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Transform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Transform.hpp
    ${CMAKE_CURRENT_LIST_DIR}/UpdateEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/UpdateEvent.hpp
)
