target_sources(ZilchScript
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchComponent.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptZilchStaticLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchScriptZilchStaticLibrary.hpp
)
