target_sources(Vulkan
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/EnumConversions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanBufferCreation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanCommandBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanDeviceQueries.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanExtensions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanImages.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanInitialization.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanLogicalDeviceCreation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanMaterials.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanMaterials.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanPhysicsDeviceSelection.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanPipeline.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanRenderer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanRendererInit.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanRenderPass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanStatus.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanStructures.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanStructures.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanSwapChain.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanSyncronization.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VulkanValidationLayers.hpp
)
