target_sources(ZilchHelpers
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchHelpersStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchCallingStateSingleton.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchModule.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchModule.hpp
)
