target_sources(Application
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Application.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Application.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ApplicationConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ApplicationConfig.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Main.cpp
)
